---
windows:
  sample-app:
    panes:
      - command: 'echo "I am a command"'
        path: '~/go'
      - command: 'which vim'
        path: '~/go'
        height: 10
      # - command: 'echo "I am a command"'
      #   path: '~/go'
      # - command: 'which vim'
      #   path: '~/go'
